django/mysite/blog/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views


from .views import (
    IndexView,
    PostDetailView,
    CategoryListView,
    CategoryPostView,
    TagListView,
    TagPostView,
    SearchPostView,
    CommentFormView,
    comment_approve,
    comment_remove,
    ReplyFormView,
    reply_approve,
    reply_remove,
    ContactFormView,
    ContactResultView,
)

app_name = 'blog'
urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name="blog/login.html"), name='login'),
    path('signup/', views.signup, name='signup'),
    path('home/', IndexView.as_view(), name='index'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('category/<str:category_slug>/', CategoryPostView.as_view(), name='category_post'),
    path('tags/', TagListView.as_view(), name='tag_list'),
    path('tag/<str:tag_slug>/', TagPostView.as_view(), name='tag_post'),
    path('search/', SearchPostView.as_view(), name='search_post'),
    path('comment/<int:pk>/', CommentFormView.as_view(), name='comment_form'),
    path('comment/<int:pk>/approve/', comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', comment_remove, name='comment_remove'),
    path('reply/<int:pk>/', ReplyFormView.as_view(), name='reply_form'),
    path('reply/<int:pk>/approve/', reply_approve, name='reply_approve'),
    path('reply/<int:pk>/remove/', reply_remove, name='reply_remove'),
    path("post/<int:pk>/like/",views.like,name="like"),
    path('contact/', ContactFormView.as_view(), name='contact_form'),
    path('contact/result/', ContactResultView.as_view(), name='contact_result'),
    path('logout/', auth_views.LogoutView.as_view(next_page="blog:login"), name='logout'),
    path('create/', views.Create.as_view(), name="create"),
]

django/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import base

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/login/', base.RedirectView.as_view(pattern_name="blog:login")),
    path('accounts/profile/', base.RedirectView.as_view(pattern_name="blog:index")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.IMAGE_URL, document_root=settings.IMAGE_ROOT)

django/mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse_lazy

# ジャンルのモデル
class Category(models.Model):
    # カテゴリ名
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    # 登録した時間
    timestamp = models.DateTimeField(auto_now_add=True)
    # adminでの表示方法
    def __str__(self):
        return self.name


# タグのモデル
class Tag(models.Model):
    # タグ名
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    # 登録した時間
    timestamp = models.DateTimeField(auto_now_add=True)

    # adminでの表示名
    def __str__(self):
        return self.name


class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    tags = models.ManyToManyField(Tag, blank=True)
    title = models.CharField(max_length=255)
    singer = models.CharField(max_length=50, default='')
    url = models.URLField(max_length=200, default='', blank=True)
    description = models.TextField()
    image = models.ImageField(
        upload_to='images', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(blank=True, null=True)
    is_public = models.BooleanField(default=False)
    like = models.IntegerField(default=0)

    class Meta:
        ordering = ['-created_at']
    
    def save(self, *args, **kwargs):
        if self.is_public and not self.published_at:
            self.published_at = timezone.now()
        super().save(*args, **kwargs)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy("blog:index")



# ブログ記事に画像を挿入する
class ContentImage(models.Model):
    # 一つの記事につき,画像は一つ
    post = models.ForeignKey(Post, on_delete=models.PROTECT)
    content_image = models.ImageField(upload_to='post_content_images/')


# コメント機能
class Comment(models.Model):
    # 投稿に対してリレーション
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=50)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['-timestamp']

    def approve(self):
        self.approved = True
        self.save()

    def __str__(self):
        return self.text


# 返信機能
class Reply(models.Model):
    # コメントに対してリレーション
    comment = models.ForeignKey(
        Comment, on_delete=models.CASCADE, related_name='replies')
    author = models.CharField(max_length=50)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    def approve(self):
        self.approved = True
        self.save()

    def __str__(self):
        return self.text

django/mysite/blog/forms.py
from django.forms import ModelForm, TextInput, Textarea, Form, CharField, PasswordInput, ValidationError, EmailField, EmailInput
from django.contrib.auth.models import User
from .models import Post, Comment, Reply
from django.conf import settings
from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse



class SignUpForm(Form):
    username = CharField(widget=TextInput)
    enter_password = CharField(widget=PasswordInput)
    retype_password = CharField(widget=PasswordInput)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise ValidationError('The username has been already taken.')
        return username

    def clean_enter_password(self):
        password = self.cleaned_data.get('enter_password')
        if len(password) < 5:
            raise ValidationError('Password must contain 5 or more characters.')
        return password

    def clean(self):
        super(SignUpForm, self).clean()
        password = self.cleaned_data.get('enter_password')
        retyped = self.cleaned_data.get('retype_password')
        if password and retyped and (password != retyped):
            self.add_error('retype_password', 'This does not match with the above.')

    def save(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('enter_password')
        new_user = User.objects.create_user(username = username)
        new_user.set_password(password)
        new_user.save()



class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('author', 'text')
        widgets = {
            'author': TextInput(attrs={
                'class': 'form-control',
                'placeholder': '名前',
            }),
            'text': Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'コメント内容',
            }),
        }
        labels = {
            'author': '',
            'text': '',
        }



class ReplyForm(ModelForm):
    class Meta:
        model = Reply
        fields = ('author', 'text')
        widgets = {
            'author': TextInput(attrs={
                'class': 'form-control',
                'placeholder': '名前',
            }),
            'text': Textarea(attrs={
                'class': 'form-control',
                'placeholder': '返信内容',
            }),
        }
        labels = {
            'author': '',
            'text': '',
        }


class ContactForm(Form):
    name = CharField(
        label='',
        max_length=100,
        widget=TextInput(attrs={
            'class': 'form-control',
            'placeholder': "お名前",
        }),
    )
    email = EmailField(
        label='',
        widget=EmailInput(attrs={
            'class': 'form-control',
            'placeholder': "メールアドレス",
        }),
    )
    message = CharField(
        label='',
        widget=Textarea(attrs={
            'class': 'form-control',
            'placeholder': "お問い合わせ内容",
        }),
    )

    def send_email(self):
        subject = "お問い合わせ"
        message = self.cleaned_data['message']
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        from_email = '{name} <{email}>'.format(name=name, email=email)
        recipient_list = [settings.EMAIL_HOST_USER]  # 受信者リスト
        try:
            send_mail(subject, message, from_email, recipient_list)
        except BadHeaderError:
            return HttpResponse("無効なヘッダが検出されました。")

django/mysite/blog/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Q
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, FormView

from .forms import CommentForm, ReplyForm, SignUpForm, ContactForm
from .models import Post, Category, Tag, Comment, Reply
from django.urls import reverse_lazy


# 個々のブログ記事のView
class PostDetailView(DetailView):
    # Postモデルを表示する
    model = Post

    # 公開されおらず、ユーザログインしていない場合はError
    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if not obj.is_public and not self.request.user.is_authenticated:
            raise Http404
        return obj


# 記事の一覧View
class IndexView(ListView):
    # Postモデルを表示する
    model = Post
    # テンプレート名
    template_name = 'blog/index.html'
    paginate_by = 3


# カテゴリ一覧View
class CategoryListView(ListView):
    # 公開済みのカテゴリの集計
    queryset = Category.objects.annotate(
        num_posts=Count('post', filter=Q(post__is_public=True)))


# タグ一覧View
class TagListView(ListView):
    # 公開済みのタグの集計
    queryset = Tag.objects.annotate(num_posts=Count(
        'post', filter=Q(post__is_public=True)))


# 特定のカテゴリにおける投稿一覧
class CategoryPostView(ListView):
    # Postモデルを表示する
    model = Post
    # テンプレート名
    template_name = 'blog/category_post.html'

    def get_queryset(self):
        category_slug = self.kwargs['category_slug']
        self.category = get_object_or_404(Category, slug=category_slug)
        qs = super().get_queryset().filter(category=self.category)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        return context


# 特定のタグにおける投稿一覧
class TagPostView(ListView):
    # Postモデルを表示
    model = Post
    # テンプレート名
    template_name = 'blog/tag_post.html'

    def get_queryset(self):
        tag_slug = self.kwargs['tag_slug']
        self.tag = get_object_or_404(Tag, slug=tag_slug)
        qs = super().get_queryset().filter(tags=self.tag)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = self.tag
        return context


# 検索機能
class SearchPostView(ListView):
    model = Post
    template_name = 'blog/search_post.html'
    paginate_by = 3

    def get_queryset(self):
        query = self.request.GET.get('q', None)
        lookups = (
            Q(title__icontains=query) |
            Q(description__icontains=query) |
            Q(category__name__icontains=query) |
            Q(tags__name__icontains=query)
        )
        if query is not None:
            qs = super().get_queryset().filter(lookups).distinct()
            return qs
        qs = super().get_queryset()
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get('q')
        context['query'] = query
        return context


def like(request,pk):
    try:
        article = Post.objects.get(pk=pk)
    except Post.DoesNotExist:
        raise Http404
    article.like += 1
    article.save()
    return redirect('blog:post_detail', pk)


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:index')
    else:
        form = SignUpForm()

    context = {'form':form}
    return render(request, 'blog/signup.html', context)


class Create(CreateView):
    model = Post
    fields = ["title", "singer", "category", "tags", "description", "url", "image", "is_public"]


class ContactFormView(FormView):
    template_name = 'blog/contact_form.html'
    form_class = ContactForm
    success_url = reverse_lazy('contact_result')

    def form_valid(self, form):
        form.send_email()
        return super().form_valid(form)


class ContactResultView(TemplateView):
    template_name = 'blog/contact_result.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['success'] = "お問い合わせは正常に送信されました。"
        return context


class CommentFormView(CreateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        comment = form.save(commit=False)
        post_pk = self.kwargs['pk']
        comment.post = get_object_or_404(Post, pk=post_pk)
        comment.save()
        return redirect('blog:post_detail', pk=post_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post_pk = self.kwargs['pk']
        context['post'] = get_object_or_404(Post, pk=post_pk)
        return context


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:post_detail', pk=comment.post.pk)
 
 
@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('blog:post_detail', pk=comment.post.pk)


class ReplyFormView(CreateView):
    model = Reply
    form_class = ReplyForm

    def form_valid(self, form):
        reply = form.save(commit=False)
        comment_pk = self.kwargs['pk']
        reply.comment = get_object_or_404(Comment, pk=comment_pk)
        reply.save()
        return redirect('blog:post_detail', pk=reply.comment.post.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comment_pk = self.kwargs['pk']
        context['comment'] = get_object_or_404(Comment, pk=comment_pk)
        return context


@login_required
def reply_approve(request, pk):
    reply = get_object_or_404(Reply, pk=pk)
    reply.approve()
    return redirect('blog:post_detail', pk=reply.comment.post.pk)


@login_required
def reply_remove(request, pk):
    reply = get_object_or_404(Reply, pk=pk)
    reply.delete()
    return redirect('blog:post_detail', pk=reply.comment.post.pk)

django/mysite/blog/templates/blog/category_list.html
{% extends "base.html" %}

{% block title %}カテゴリ一覧 | {{ block.super }}{% endblock %}
{% block description %}カテゴリ一覧ページです。{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-md-8">
      <h1 class="mb-4">カテゴリ一覧</h1>
      {% include "blog/snippets/pagination_b.html" %}
      <ul class="list">
  　　　　{% for category in object_list %}
  　　　　<li><a href="{% url 'blog:category_post' category.slug %}">{{ category.name }} ({{ category.num_posts }})</a></li>
  　　　　{% empty %}
  　　　　<li>カテゴリはありません。</li>
  　　　　{% endfor %}
　　　　</ul>
    </main>
    <aside class="col-md-4">
      {% include "blog/snippets/sidebar.html" %}
    </aside>
  </div>
</div>
{% endblock %}

django/mysite/blog/templates/blog/category_post.html
{% extends "base.html" %}

{% block title %}{{ category.name }} | {{ block.super }}{% endblock %}
{% block description %}「{{ category.name }}」の投稿一覧ページです。{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-md-8">
      <h1 class="mb-4">「{{ category.name }}」の投稿一覧</h1><br><br>
      {% include "blog/snippets/main_post_list.html" %}
    </main>
    <aside class="col-md-4">
      {% include "blog/snippets/sidebar.html" %}
    </aside>
  </div>
</div>
{% endblock %}

django/mysite/blog/templates/blog/comment_form.html
{% extends "base.html" %}

{% block title %}コメント投稿フォーム | {{ block.super }}{% endblock %}
{% block description %}コメント投稿フォームのページです。{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-md-8">
      <h1 class="mb-4">コメント投稿フォーム</h1>
      <div class="comment">
        <p style="font-size: larger;">To:「{{ post.title }}」</p><br>
        <form method="POST">{% csrf_token %}
          {{ form.as_p }}<br>
          <button type="submit" class="btn btn-primary">送信</button>
        </form>
      </div>
    </main>
    <aside class="col-md-4">
      {% include "blog/snippets/sidebar.html" %}
    </aside>
  </div>
</div>
{% endblock %}

django/mysite/blog/templates/blog/contact_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}お問い合わせフォーム | {{ block.super }}{% endblock %}
{% block description %}お問い合わせフォームのページです。{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-md-8">
      <h1 class="mb-4">お問い合わせ</h1>
      <div class="contact">
        <form method="POST">{% csrf_token %}
          <div class="form-group row">
            <div class="col-sm-9">
                {{ form.name|add_class:'form-control' }}
                {% for error in form.name.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
            </div>
        </div>
        <br>
        <div class="form-group row">
            <div class="col-sm-9">
                {{ form.email|add_class:'form-control' }}
                {% for error in form.email.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
            </div>
        </div>
        <br>
        <div class="form-group row">
            <div class="col-sm-9">
                {{ form.message|add_class:'form-control' }}
                {% for error in form.message.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
            </div>
        </div>
        <br>
        <button type="submit" class="btn btn-primary">送信</button>
        </form>
      </div>
    </main>
    <aside class="col-md-4">
      {% include "blog/snippets/sidebar.html" %}
    </aside>
  </div>
</div>
{% endblock %}

django/mysite/blog/templates/blog/contact_result.html
{% extends "base.html" %}

{% block content %}
{{ success }}
{% endblock %}

django/mysite/blog/templates/blog/index.html
{% extends "base.html" %}

{% block title %}投稿一覧 | {{ block.super }}{% endblock %}
{% block description %}マイブログです。毎日更新します。{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-md-8">
      <h1 class="mb-4">投稿一覧</h1>
      {% include "blog/snippets/main_post_list.html" %}
      {% include "blog/snippets/pagination_b.html" %}
    </main>
    <aside class="col-md-4">
      {% include "blog/snippets/sidebar.html" %}
    </aside>
  </div>
</div>
{% endblock %}

django/mysite/blog/templates/blog/login.html
{% extends "base_2.html" %}
{% load widget_tweaks %}

{% block title %}ログイン | {{ block.super }}{% endblock %}
{% block description %}ログインページです。{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-md-8">
      <h1 class="mb-4">ログイン</h1>
      <div class="comment_login">
        <form action="{% url 'blog:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group row">
            <label for="{{ form.username.id_for_label }}" class="col-sm-3 col-form-label">ユーザ名</label>
            <div class="col-sm-9">
                {{ form.username|add_class:'form-control' }}
                {% for error in form.username.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
            </div>
        </div>
        <br>
        <div class="form-group row">
            <label for="{{ form.password.id_for_label }}" class="col-sm-3 col-form-label">パスワード</label>
            <div class="col-sm-9">
                {{ form.password|add_class:'form-control' }}
                {% for error in form.password.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
            </div>
        </div>
        <br><br>
        <input type="submit" value="Login">
        </form><br>
        <p>アカウントをお持ちでない方は<a href= "{% url 'blog:signup' %}" class="account" >こちら</a></p>
      </div>
    </main>
    <aside class="col-md-4">
      
    </aside>
  </div>
</div>
{% endblock %}

django/mysite/blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %}{{ object.title }} | {{ block.super }}{% endblock %}
{% block description %}{{ object.description }}{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-md-8">
      <article class="blog-area">
        {% if object.image %}
        <img class="card-img-top" src="{{ object.image.url }}" alt="{{ object.title }}">
        {% endif %}
        <hr><br>
        <h1 class="detail_title">タイトル : {{ object.title }}</h1>
        <br>
        <h1 class="detail_title">歌手名 : {{ object.singer }}</h2>
        <br><br><br>
        <div style="font-size: 20px;">
        <a href="{% url 'blog:category_post' object.category.slug %}"><p>カテゴリ 　: 　{{ object.category.name }}</p></a>
        {% for tag in object.tags.all %}
        <a href="{% url 'blog:tag_post' tag.slug %}">#{{ tag.name }}</a>　
        {% endfor %}
        <br><br><br>
        <u><a>投稿者のコメント</a></u>
        <br><br>
        <a>　　{{ object.description|safe }}</a>
        </div>
        <br><br>
        <div class="embed-responsive embed-responsive-16by9">
          <iframe class="embed-responsive-item" src="{{ object.url|safe }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
        <hr>
        <p class="good"><a href="{% url 'blog:like' post.pk %}"><span id="like">{{ post.like }}</span>&nbsp;&nbsp;いいね！</a></p>
        <p>投稿日 : {{ object.published_at|date }}</p>
      </article>
      <article class="comment-area">
        <a class="btn btn-primary my-3" href="{% url 'blog:comment_form' post.pk %}">コメントを投稿する</a>
        {% include "blog/snippets/comments.html" %}
      </article>
    </main>
    <div class="col-md-4">
      {% include "blog/snippets/sidebar.html" %}
    </div>
  </div>
</div>
{% endblock %}

django/mysite/blog/templates/blog/reply_form.html
{% extends "base.html" %}

{% block title %}コメント返信フォーム | {{ block.super }}{% endblock %}
{% block description %}コメント返信フォームのページです。{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-md-8">
      <h1 class="mb-4">コメント返信フォーム</h1>
      <div class="comment">
        <p>To: {{ comment.author }}さん</p>
        <p class="text-white-100">{{ comment.text|linebreaksbr }}</p>
        <form method="POST">{% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary">送信</button>
        </form>
      </div>
    </main>
    <aside class="col-md-4">
      {% include "blog/snippets/sidebar.html" %}
    </aside>
  </div>
</div>
{% endblock %}

django/mysite/blog/templates/blog/search_post.html
{% extends "base.html" %}

{% block title %}{% if query %}{{ query }}{% endif %} | {{ block.super }}{% endblock %}
{% block description %}検索ワード「{% if query %}{{ query }}{% endif %}」での検索結果ページです。{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-md-8">
      <h1 class="mb-4">「{% if query %}{{ query }}{% endif %}」の検索結果</h1>
      <p class="text-right">{{ page_obj.start_index }}-{{ page_obj.end_index }}件（{{ paginator.count }}件）</p>
      {% include "blog/snippets/main_post_list.html" %}
      {% include "blog/snippets/pagination_b.html" %}
    </main>
    <aside class="col-md-4">
      {% include "blog/snippets/sidebar.html" %}
    </aside>
  </div>
</div>
{% endblock %}

django/mysite/blog/templates/blog/signup.html
{% extends "base_2.html" %}
{% load widget_tweaks %}

{% block title %}アカウント作成 | {{ block.super }}{% endblock %}
{% block description %}アカウント作成ページです。{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-md-8">
      <h1 class="mb-4">アカウント作成</h1>
      <div class="comment_login">
        <form action="{% url 'blog:signup' %}" method="post">
        {% csrf_token %}
        <div class="form-group row">
            <label for="{{ form.username.id_for_label }}" class="col-sm-3 col-form-label">ユーザ名</label>
            <div class="col-sm-9">
                {{ form.username|add_class:'form-control' }}
                {% for error in form.username.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
            </div>
        </div>
        <br>
        <div class="form-group row">
            <label for="{{ form.enter_password.id_for_label }}" class="col-sm-3 col-form-label">パスワード</label>
            <div class="col-sm-9">
                {{ form.enter_password|add_class:'form-control' }}
                {% for error in form.enter_password.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
            </div>
        </div>
        <br>
        <div class="form-group row">
            <label for="{{ form.retype_password.id_for_label }}" class="col-sm-3 col-form-label">もう一度入力</label>
            <div class="col-sm-9">
                {{ form.retype_password|add_class:'form-control' }}
                {% for error in form.retype_password.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
            </div>
        </div>
        <br><br>
        <input type="submit" value="Sign Up">
        </form><br>
        <a href= "{% url 'blog:login' %}">戻る</a>
      </div>
    </main>
    <aside class="col-md-4">
      
    </aside>
  </div>
</div>
{% endblock %}

django/mysite/blog/templates/blog/tag_list.html
{% extends "base.html" %}

{% block title %}タグ一覧 | {{ block.super }}{% endblock %}
{% block description %}タグ一覧ページです。{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-md-8">
      <h1 class="mb-4">#タグ一覧</h1>
      {% include "blog/snippets/pagination_b.html" %}
      <ul class="list">
  　　　　{% for tag in object_list %}
  　　　　<li><a href="{% url 'blog:tag_post' tag.slug %}">#{{ tag.name }} ( {{ tag.num_posts }} )</a></li>
　　　　　{% empty %}
  　　　　<li>タグはありません。</li>
  　　　　{% endfor %}
　　　　</ul>
    </main>
    <aside class="col-md-4">
      {% include "blog/snippets/sidebar.html" %}
    </aside>
  </div>
</div>
{% endblock %}

django/mysite/blog/templates/blog/tag_post.html
{% extends "base.html" %}

{% block title %}#{{ tag.name }} | {{ block.super }}{% endblock %}
{% block description %}「{{ tag.name }}」の投稿一覧ページです。{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-md-8">
      <h1 class="mb-4">「#{{ tag.name }}」の投稿一覧</h1><br><br>
      {% include "blog/snippets/main_post_list.html" %}
    </main>
    <aside class="col-md-4">
      {% include "blog/snippets/sidebar.html" %}
    </aside>
  </div>
</div>
{% endblock %}