django/mysite/blog/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views


from .views import (
    IndexView,
    PostDetailView,
    CategoryListView,
    CategoryPostView,
    TagListView,
    TagPostView,
    SearchPostView,
    CommentFormView,
    comment_approve,
    comment_remove,
    ReplyFormView,
    reply_approve,
    reply_remove,
    ContactFormView,
    ContactResultView,
)

app_name = 'blog'
urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name="blog/login.html"), name='login'),
    path('signup/', views.signup, name='signup'),
    path('home/', IndexView.as_view(), name='index'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('category/<str:category_slug>/', CategoryPostView.as_view(), name='category_post'),
    path('tags/', TagListView.as_view(), name='tag_list'),
    path('tag/<str:tag_slug>/', TagPostView.as_view(), name='tag_post'),
    path('search/', SearchPostView.as_view(), name='search_post'),
    path('comment/<int:pk>/', CommentFormView.as_view(), name='comment_form'),
    path('comment/<int:pk>/approve/', comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', comment_remove, name='comment_remove'),
    path('reply/<int:pk>/', ReplyFormView.as_view(), name='reply_form'),
    path('reply/<int:pk>/approve/', reply_approve, name='reply_approve'),
    path('reply/<int:pk>/remove/', reply_remove, name='reply_remove'),
    path("post/<int:pk>/like/",views.like,name="like"),
    path('contact/', ContactFormView.as_view(), name='contact_form'),
    path('contact/result/', ContactResultView.as_view(), name='contact_result'),
    path('logout/', auth_views.LogoutView.as_view(next_page="blog:login"), name='logout'),
    path('create/', views.Create.as_view(), name="create"),
]

django/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import base

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/login/', base.RedirectView.as_view(pattern_name="blog:login")),
    path('accounts/profile/', base.RedirectView.as_view(pattern_name="blog:index")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.IMAGE_URL, document_root=settings.IMAGE_ROOT)

django/mysite/templates/base/navbar.html
{% load static %}
<link rel="stylesheet" href="{% static 'blog/css/nav.css' %}">

<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
  <a class="navbar-brand" href="/home/">MyMusic</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/home/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:category_list' %}">Categories</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:tag_list' %}">Tags</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:create' %}">Post</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Accounts
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'blog:login' %}">別のアカウントでログイン</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'blog:logout' %}">ログアウト</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:contact_form' %}">Contact</a>
      </li>
    </ul>
    {% include "blog/snippets/search_form.html" %}
  </div>
</nav>

django/mysite/templates/base/navbar_2.html
{% load static %}
<link rel="stylesheet" href="{% static 'blog/css/nav.css' %}">

<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
  <a class="navbar-brand" href="#">MyMusic</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</nav>